# Generated by Django 5.2.4 on 2025-08-16 17:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_remove_prediction_result_prediction_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresponse',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('f0efdd2c-4c72-47cf-969f-04646783ca00'), editable=False, primary_key=True, serialize=False),
        ),
    ]
