# Generated by Django 5.2.4 on 2025-08-17 05:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0004_alter_predictionresponse_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictionresponse',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
